### ISSUE TITLE
TA31RCO-RMR Wrong locked zeroing at the acog and on top red dot

### ISSUE THREAD

**Issue by xDBurrachaxD** [RHSMODS/statusquo#1012]
The acog is locked at 100m, supposed to be 300m
The Red Dot on top of it is locked at 300m, supposed to me 100m

![20241119161549_1](https://github.com/user-attachments/assets/8baddeb0-105e-41ee-b749-663a2c174aa4)
![20241119161552_1](https://github.com/user-attachments/assets/f2a61b04-7862-491c-9ac7-5737a567e0dc)

**Comment by da12thMonkey** [comment]
Not a bug
![acog](https://github.com/user-attachments/assets/cd7e8157-e94b-428d-91b2-ce6dd9785856)

**Comment by ajvorobiev** [comment]
@xDBurrachaxD btw also your shots seem to be from Arma 3. Support for Arma 3 version of RHS has been stopped and this issue tracker is purely for the Reforger Status Quo mod.
