### ISSUE TITLE
Helmet Sizes

### ISSUE THREAD

**Issue by Causeofdeath745** [RHSMODS/statusquo#1018]
![image](https://github.com/user-attachments/assets/36980acc-dc14-4cee-9a06-728b31e7a655)
One thing I noticed, when compared to other mods, The ACH, MICH, helmets, including ones with the covers for them, look very very tiny on the players head. Where I took the same helmet with another mod and it looks more proportionate to the head and body compared to the RHS. Is it possible to change the size of the helmets to be more form fitting? Thank you so much!

Nameless mod : 
![image](https://github.com/user-attachments/assets/48660652-1789-43bb-9f59-222feac87ec2)

RHS:
![image](https://github.com/user-attachments/assets/1a440e8f-4b9e-490f-bdca-2e17aa5acd1e)

Both: 
![image](https://github.com/user-attachments/assets/2f14cb97-1824-48fd-b68b-3c9fb0e65d14)

**Comment by ajvorobiev** [comment]
I don't see it sorry. The helmet have correct sizes, but not all are for the same head size (M, L, XL..). Also Arma heads are all over the place.
