### ISSUE TITLE
GM Entity Label swap & animation issue: USAF faction

### ISSUE THREAD

**Issue by JLuna25** [RHSMODS/statusquo#1021]
within GM: under USAF faction, multiple options are available for supply drops rather than the intended faction specific option. AFRF & USAF supply drops both exist however the contents are backwards. 

The actual airborne drop animation is functional & required for the AFRF drop (labeled as USAF & under the USAF faction) but the USAF drop (labeled as AFRF) is able to be placed directly
![RHSicon](https://github.com/user-attachments/assets/a6e8ef9c-7253-499c-b2af-67810110da05)

![image](https://github.com/user-attachments/assets/4204dc49-f0da-4c3e-90e8-c4fddfcda81e)

![image](https://github.com/user-attachments/assets/d7cedfeb-bba0-4d22-84fa-ebfeb89ff8c9)

**Comment by JLuna25** [comment]
Additional info: When both objects are down, contain the AFRF supply drop icons

![image](https://github.com/user-attachments/assets/6435ff26-7395-4200-9006-772c4c0af435)

**Comment by JLuna25** [comment]
Under AFRF faction: issue does not persist with multiple options, however box is mislabeled as "USAF supply box" rather than AFRF. No airborne drop animation

![image](https://github.com/user-attachments/assets/093c7160-444e-4b9e-b525-ee22c32c81ce)

![image](https://github.com/user-attachments/assets/1efcc67a-90ac-4a72-a091-9bb71c9120dd)

**Comment by odkupiciel375** [comment]
> Additional info: When both objects are down, contain the AFRF supply drop icons
taht is an amunition crate icon not AFRF

**Comment by ajvorobiev** [comment]
Fixed in r3934
