### ISSUE TITLE
Now Broken on Xbox after Update

### ISSUE THREAD

**Issue by CMDRLEOPARD888** [RHSMODS/statusquo#1024]
So me and my group play on Xbox.  The mod is unable to be updated or downloaded after the recent update.  When you attempt to download it, it simply says "The response from the server took too long" and to check your internet connection.  This is a problem for every member of my group, across Xbox series S and X.  

I've also noticed that the servers we usually frequent that use RHS have record low player counts, leading me to believe this may be an issue isolated to just the Xbox platform.

**Comment by odkupiciel375** [comment]
Report this to BI not to us as we dont have any influence on BIs backend
