### ISSUE TITLE
RHS + Zeliks Character

### ISSUE THREAD

**Issue by iTzManic** [RHSMODS/statusquo#1025]
When loading both of these mods together, The inventory has errors from an RHS script. + All items in the inventory go into 1 slot. Top left corner.

**Comment by ajvorobiev** [comment]
Someone suggested a fix

![image](https://github.com/user-attachments/assets/92348772-a24b-4b02-9bd5-17eac291554f)

either way we do not provide maintenance for compatibility with other mods.
