### ISSUE TITLE
CTD Smaw MBS

### ISSUE THREAD

**Issue by tacticaltoxic** [RHSMODS/statusquo#1028]
repro:
CTD Smaw:

1. Spawn, enter a vehicle with smaw in hands
2. Exit a vehicle smaw in hands
3. Try to range distance to ANY vehicle (not terrain or prop)
4. CTD

**Comment by ajvorobiev** [comment]
I cant reproduce this. Is it fixed or do you need better reproduction steps?

**Comment by ajvorobiev** [comment]
Solved for now with a hack for vanilla bug. See r3951.
