### ISSUE TITLE
Unable to reload while aiming on updated controls

### ISSUE THREAD

**Issue by Pycera** [RHSMODS/statusquo#1030]
Unable to reload while aiming on updated controls first clip is with no mods installed, second clip is with only RHS installed

https://github.com/user-attachments/assets/4e1a22c6-e87f-4ef9-ab32-df06c44f09b4

https://github.com/user-attachments/assets/ea324fc2-87f3-4f97-a1f8-c636db6a01f7

**Comment by ajvorobiev** [comment]
Cant reproduce as of r4001. Vanilla weaponsas well as RHS guns can reload while in ADS.
