### ISSUE TITLE
Black screen when in a vehicle crash as passenger

### ISSUE THREAD

**Issue by Cthorlhu** [RHSMODS/statusquo#1031]
When you are a passenger in a vehicle (tested on vanilla helis, vanilla humvees, AH6M heli) and that vehicle explodes it will cause passengers (not the driver) to go to a black screen that is unrecoverable until you log back in.

To test this I loaded my player character into the passenger seat of any of these vehicles and dropped them from a height guaranteed to make them explode but not so high they glitch through the ground. Every single time it caused my player to go to the black screen.... in the logs the head dev in my team gets this error 

---------------------------------------
Reason: NULL pointer to instance. Variable 'm_pCharacterEntity'

Class:      'SCR_DepthOfFieldEffect'
Function: 'GetDOFType'
Stack trace:
Scripts/Game/UI/ScreenEffects/RHS_M_DepthOfFieldEffect.c:6 Function GetDOFType
Scripts/Game/UI/ScreenEffects/SCR_DepthOfFieldEffect.c:139 Function UpdateEffect
Scripts/Game/UI/ScreenEffectsManager.c:67 Function DisplayUpdate
Scripts/Game/UI/HUD/SCR_InfoDisplayExtended.c:551 Function UpdateValues
23:36:34.756 WORLD        : UpdateEntities
23:36:34.756  WORLD        : PostFrame
23:36:34.756   SCRIPT    (E): Virtual Machine Exception
---------------------------------------

after this happens this player entity gets several database entries (level and bank) erased or changed and they no longer get access to it (3 entries per char, level, inventory, bank)

any insight on this would be appreciated

**Comment by iTzManic** [comment]
Valid ^ When in a passenger seat, and the vehicle blows up you get the above error. (On our server it leaves you at a black screen and you can't do anything but I just tested with just stock RHS and same thing happens)

**Comment by iTzManic** [comment]
modded class SCR_DepthOfFieldEffect : SCR_BaseScreenEffect
{
	override DepthOfFieldTypes GetDOFType(out bool isNearDOFAllowed, bool settingsChanged = false)
	{
		BaseWeaponManagerComponent weaponManager = m_pCharacterEntity.GetCharacterController().GetWeaponManagerComponent();
		if (weaponManager)
		{
			SightsComponent sights = weaponManager.GetCurrentSights();
			if (!sights || sights.RHS_IsDOFDisabled())
			{
				isNearDOFAllowed = false;
				m_iNeededDofType = m_iDesiredDofType;
				return m_iDesiredDofType;
			}
		}
		return super.GetDOFType(isNearDOFAllowed,settingsChanged);
	}
}
