### ISSUE TITLE
Suppressors

### ISSUE THREAD

**Issue by ajvorobiev** [RHSMODS/statusquo#167]
### Injection and configuration
- [x] SR-3M suppressor
- [x] PBS-4
- [x] TGP-A
- [x] KAC NT4
- [x] Surefire SOCOM RC2
- [x] Surefire SOCOM RC3
- [x] Surefire FA762SS

### Needing muzzle slot configuration
- [x] SR-3M
- [x] AK-74M
- [x] AKS-74UN
- [x] AK-105
- [x] M4
- [x] M27/M38
- [x] M40A5

**Comment by ajvorobiev** [comment]
I think we need to rename this to a 5.45 silencer.

**Comment by da12thMonkey** [comment]
Task complete until additional weapons and suppressors are added
