### ISSUE TITLE
AN/PEQ-15

### ISSUE THREAD

**Issue by gurdyboy** [RHSMODS/statusquo#187]

**Comment by ajvorobiev** [comment]
https://www.haho.online/post/review-an-peq-15-atpial-advanced-target-pointer-illuminator-aiming-laser

**Comment by ajvorobiev** [comment]
Docs: https://docs.rhsmods.org/rhs-status-quo-user-documentation/arma-reforger/rhs-status-quo/blufor/weapons/attachments/lasers/an-peq-16a
