### ISSUE TITLE
K17 SuperTask

### ISSUE THREAD

**Issue by tacticaltoxic** [RHSMODS/statusquo#237]
APS system - [ ] 
Thermal scopes - [X] 
NVG scopes - [X] 
Proper HUD  and Optic - [X] 
Commander seat and turret(epoch) - [X] 
Commander seat and turret(berezhok) - [X] 
Gun physical recoil - [X] 
Stabilization system - [X] 
Ammo selection system - [X] 
Interior - [X] 
Integrated radio - [ ] 
Smoke dispensers - [X] 
Damaged model for both Turrets - [X]

**Comment by JiraF4** [comment]
TODO: add damaged turret models
