### ISSUE TITLE
Possible Crashes 

### ISSUE THREAD

**Issue by TrippyDG** [RHSMODS/statusquo#315]
[error 2.log](https://github.com/RHSMODS/statusquo/files/11772656/error.2.log)
Doing this off my phone but I was trying to take a look into it and I saw some things about NVGs, we ended up taking out them in our server and it seems to be running fine this morning. Appreciate you looking at this and if it’s not on your end then I’ll take a deeper look. Server didn’t crash but lots of Disconnects and player crashes

**Comment by reyhard** [comment]
What mods are being used? Seems one of the mods, which adds RHS stuff to vanilla soviet crates is using wrong items, which causes that issue

**Comment by TrippyDG** [comment]
Hey sorry I haven’t replied, had a concert I had to perform at, but I can get you a list if needed, but overall NVGs have been a issue for us at least on a modded conflict

**Comment by reyhard** [comment]
Most likely it is caused by mod, which is adding RHS items to the create. According to the logs you were using one of the test NVGs which should not be used in game and which are not found in RHS crates.

**Comment by ajvorobiev** [comment]
As mentioned most likely other mod responsible.
