### ISSUE TITLE
User can open multiple radial menus at the same time

### ISSUE THREAD

**Issue by odkupiciel375** [RHSMODS/statusquo#375]
If user holds [\\] key to open RHS radial menu then if he presses [G] it will open radio radial menu which will be on top of RHS radial menu.
![image](https://github.com/RHSMODS/statusquo/assets/19805800/dd674ac0-8fd0-41e0-a835-7f0c76fc0c1d)

Its probably a good idea to check if its not the same with vaila menus fe. radio + something (i dont know of any other vanila radial menus)

**Comment by odkupiciel375** [comment]
yes
![20231210150529_1](https://github.com/RHSMODS/statusquo/assets/19805800/97e9dc6b-ddd2-4b93-8490-a0dda4e6c800)

**Comment by ajvorobiev** [comment]
Seems fine now.
