### ISSUE TITLE
NVG usable with Binos/LRF

### ISSUE THREAD

**Issue by odkupiciel375** [RHSMODS/statusquo#385]
User can see with his NV effect while being ADS with his binos/lrf

**Comment by ajvorobiev** [comment]
I wonder whether this one we can actually leave. I think technically not impossible to do this irl, Might be awkward but not impossible?? What do you think?

**Comment by Pnuky** [comment]
It's quite bad to achieve but It's not impossible.

**Comment by ajvorobiev** [comment]
Lets keep.
