### ISSUE TITLE
Rhino Component should take universal parameters

### ISSUE THREAD

**Issue by Pnuky** [RHSMODS/statusquo#401]
Now Rhino Component has defined L4G24_ARM as a string that is targeting .pap file in order to animate it.

Solutions:
1. As discussed with Red - we should rename bones responsible for lowering/rising nvgs to same for every rhino type mounts.
2. Make it as a input field to define a target in designated .pap file.

**Comment by odkupiciel375** [comment]
1) There is no need for a unified bone structure.
2) I'll make the signal name constant "NVG_FOLD".
In turn, this will work like so: The code will always send only 1 or 0 to the signal called "NVG_FOLD", which will then be calculated by the sig file that is used by the pap file. Each NVG will be able to use a separate pap file, as that will allow for different procedural animations. For example, in the case of PVS31, it can fold up and rotate tubes to the sides.
