### ISSUE TITLE
Light entities arent spawned when the game is generating previews for the loadout selection screen

### ISSUE THREAD

**Issue by odkupiciel375** [RHSMODS/statusquo#404]
![image](https://github.com/RHSMODS/statusquo/assets/19805800/0ec15696-357d-4219-96ac-e0add767c7e1)
Temporarily, Debug.Error was changed to Print to prevent throwing exceptions, but I need to see how to detect if light entities should be there. RHS_LightDevice.EOnInit=>if (!slot.GetLightEntity())

**Comment by ajvorobiev** [comment]
Is this still relevant?
