### ISSUE TITLE
Inconsistent magnification on 4x optic

### ISSUE THREAD

**Issue by TokaiTeio6104** [RHSMODS/statusquo#448]
the SU-230 appear much more zoomed out than the M7RCO does even though both of them have 4x magnification. 
[M7RCO](https://cdn.discordapp.com/attachments/373534109332406273/1140026036436873307/12-08-2023_8-18-04_PM-m533qqla.png)
[SU-230](https://cdn.discordapp.com/attachments/373534109332406273/1140026036847919144/12-08-2023_8-17-51_PM-yfqvl0q5.png)

**Comment by ajvorobiev** [comment]
judging by the state of the RCO reticle, it is incorrect after the last patch.

**Comment by ajvorobiev** [comment]
Should be a lot more consistent in the next patch. And the rest of 4x scopes too.

(beware that github resizes images)

![image](https://github.com/RHSMODS/statusquo/assets/7216776/2ffc50a8-2a39-4003-b32c-1adb9d37e414)
![image](https://github.com/RHSMODS/statusquo/assets/7216776/7575045b-9f3d-4cb3-9389-e2f9d7f3dd84)
