### ISSUE TITLE
Body armor blocks bullets completely.

### ISSUE THREAD

**Issue by Rebitaay** [RHSMODS/statusquo#464]
Playing with RHS, I noticed it is extremely difficult to kill enemies unless they are shot in the limbs or head.

Upon testing with only RHS enabled, I found that the Russian 6B45 and the USMC PC Gen III both block bullets completely, infinitely, and without causing any blunt force trauma, which means that the soldier is entirely impervious to damage when shot in the armored areas.

I can reproduce this 100% of the time. You can see the issue here, using the PKM and M249: https://youtu.be/ARF4JhitOk4

Other unrecorded tests with different weapons had the same results.

**Comment by ajvorobiev** [comment]
As weird as it sounds it's working as it should be on our end. Class 5 plates that we use can withstand normal 5.45/5,56/7.62 rounds to a certain extent. Only thing that can penetrate is AP 7,62x54. With that being said, normally these plates should still cause blunt force damage and degrade over span of impacts, These are missing vanilla features that we hope the game developers can implement in the future, or we might mod it in, but either way it needs to be made separately.

Furthermore we are working on configuring more modern AP rounds of smaller calibers which should damage plates correctly. This will be added soon, but doesn't take away the fact that the player should know the rounds they use.

**Comment by ajvorobiev** [comment]
I leave this issue open so that we close it when it works correctly, but the fix is not to tweak the plates.

**Comment by ajvorobiev** [comment]
> Hello, is it possible if I can get the files for the armor so I can remove the collider temporarily so that we can shoot through the armor? Or perhaps if we can have a temporary hot fix to just remove the collider plates until a system can be put into place to work with them?

Also we are already working on AP rounds that should be used anyway. This should be added very soon.

**Comment by Rebitaay** [comment]
> I suppose that it looks broken only in dry tests, but its not that noticeable when you just play. Due netcode imperfection, and its current state its actually a miracle for plates to actually work in MP with real players.


Sorry if this is not the place for it, but I strongly disagree. I only found this "bug" and opened the issue because of how frustrating it is to use RHS after 30 hours of actual play, specifically because of armor behavior.

It may be exacerbated by the fact that I only play against AI locally or on a private server, but that community should be kept in mind. Perhaps a compromise between realism and better playability can be made until the armor is fully functioning as envisioned.

Either way, I look forward to the AP rounds. Hopefully they'll alleviate the problem.

**Comment by ajvorobiev** [comment]
> > I suppose that it looks broken only in dry tests, but its not that noticeable when you just play. Due netcode imperfection, and its current state its actually a miracle for plates to actually work in MP with real players.
> 
> Sorry if this is not the place for it, but I strongly disagree. I only found this "bug" and opened the issue because of how frustrating it is to use RHS after 30 hours of actual play, specifically because of armor behavior.
> 
> It may be exacerbated by the fact that I only play against AI locally or on a private server, but that community should be kept in mind. Perhaps a compromise between realism and better playability can be made until the armor is fully functioning as envisioned.
> 
> Either way, I look forward to the AP rounds. Hopefully they'll alleviate the problem.

Today's update to dev version of the mod adds a new plate degradation mechanism to the 6B45. If you have a chance to test it it would be awesome. Application to the USMC plate carrier and new AP rounds should come in the following days and then if everything checks out should land on stable soon!

**Comment by ajvorobiev** [comment]
New armor degradation and new rounds will be part of next stable release.
