### ISSUE TITLE
UH-1Y/AH-1Z Observer/Gunner Camera (RHSUSAF)

### ISSUE THREAD

**Issue by rco-titus** [RHSMODS/statusquo#538]
Is it possible to remove the greyscale from these optics? I noticed that on the AH-1Z the pilot can view the camera without having the greyscale, I also noticed in the AH-1Z the pilot has a greater render distance with the camera, I was able to spot IEDs on a road while my co-pilot was unable to see then due to the camera having a lower render distance on top of the greyscale being very hard to distinguish between colors, to test this we also matched our settings and tried again and still the same results so it has to be something with the camera. UH-1Y also has the same greyscale as well which makes spotting targets from a distance very hard.

So again could the greyscale be removed or maybe add an option to use either a colored optic or a b/w optic?

**Comment by reyhard** [comment]
there is no UH-1Y/AH-1Z in RHS Status Quo (this github is only for Status Quo bugs)

**Comment by rco-titus** [comment]
where should I go for the RHSUSAF mod for arma 3 then?
