### ISSUE TITLE
MS2000 is unreliable

### ISSUE THREAD

**Issue by odkupiciel375** [RHSMODS/statusquo#541]
sometimes it will turn on and sometimes it wont

**Comment by ajvorobiev** [comment]
In MP or in WB too?

**Comment by odkupiciel375** [comment]
> In MP or in WB too?

for sure in MP havent had time to test it in WB

**Comment by ajvorobiev** [comment]
Spitballing here, do you remember whether you have had another LightDevice on you at the same time like an AN/PEQ? I was looking at the on screen helpers stuff for light devices and have a feeling that if you have 2 light devices on you (helm and weapon) the keybindings might interfere?

**Comment by ajvorobiev** [comment]
seems to have worked fine yesterday. Perhaps we can close this.

**Comment by odkupiciel375** [comment]
Cannot reproduce the issue
