### ISSUE TITLE
all slotted stuff dropped on ground after reconnect or spawning with saved loadout

### ISSUE THREAD

**Issue by tacticaltoxic** [RHSMODS/statusquo#544]
![Image](https://github.com/RHSMODS/statusquo/assets/48031677/c6ef489b-edf8-415a-a437-52edc7d359e2)

**Comment by reyhard** [comment]
https://discord.com/channels/105462288051380224/1025131938207498422/1168147848341229599 engine bug - should be fixed in some patch
