### ISSUE TITLE
Light device shortcuts not working for helmet attachments

### ISSUE THREAD

**Issue by ajvorobiev** [RHSMODS/statusquo#547]
The helmet light devices like MS2k are not reacting to LD keybindings like toggle mode or state. I think initially that was supposed to be the case.

Few things to keep in mind:

- [] Figure out what to so when you have a helmet device and weapon device at the same time
- [] Uncomment stuff in `RHS_CharacterHasLightDeviceCondition` to enable shortcut hints for helmets (logic is there but turned off)

**Comment by odkupiciel375** [comment]
Attachments like the MS2000 and VIP strobe pack were not meant to be toggled/manipulated with a keybinds and are intended to be operated via user actions (e.g., when on the ground) or the radial menu. Thus, I believe that this is not the issue and should be closed.
