### ISSUE TITLE
Perst Classic gen 4.0

### ISSUE THREAD

**Issue by Brungar** [RHSMODS/statusquo#570]
Perst Classic gen 4.0  cannot be installed on weapons

**Comment by ajvorobiev** [comment]
can you please elaborate? here it is on an AN-94

![Screenshot 2023-11-13 215235](https://github.com/RHSMODS/statusquo/assets/7216776/d67b3141-70e4-43a4-91e7-9d2a4857f3a8)

Here it is on an M4A1

![Screenshot 2023-11-13 215235](https://github.com/RHSMODS/statusquo/assets/7216776/6a5b024b-1503-412f-9eb2-4d88fe699c9c)

If you are trying to say that we currently don't have many RU weapons with front rails that is another issue, but it will be dealt with separately.

**Comment by Brungar** [comment]
Got it, thanks for the clarification.
