### ISSUE TITLE
Modular Vests/Plate Carrier and Belts 

### ISSUE THREAD

**Issue by ahmed007boss** [RHSMODS/statusquo#581]
Some vests can follow a modular system such as PALS (Pouch Attachment Ladder System), which allows players to customize their vests with different types of attachments. PALS provides a grid of webbing that allows for the attachment of various pouches and accessories using compatible fasteners, such as MOLLE (Modular Lightweight Load-carrying Equipment) straps. This modular design gives players the freedom to configure their vests according to their specific needs and play style, offering flexibility and adaptability in the virtual battlefield.

Different vests in the game may follow different attachment systems. While many vests utilize the PALS (Pouch Attachment Ladder System) or MOLLE (Modular Lightweight Load-carrying Equipment) system, there are also other proprietary attachment systems used by specific vests. These systems may have their own unique design and attachment methods, offering players a variety of options when it comes to customizing their gear. It's important for players to consider the compatibility of attachments with their specific vest and choose attachments that are designed to work with the attachment system used by their vest.

Player may utilize an advanced interface, similar to a weapon inspection mode, to customize their vest and attachments. Additionally, certain vests or plate carriers may come with predefined customizations, similar to how some weapons have preconfigured attachments and customization options.

Below a vest that follow MOLLE system without any attachments 
![download (1)](https://github.com/RHSMODS/statusquo/assets/20624652/85e0091d-7292-4a93-ad23-80eb39d3e930)

Below MOLLE grids of webbing, which are based on 25 mm (1 in) wide webbing with 38 mm (1.5 in) spacing between each sewing point.
![image](https://github.com/RHSMODS/statusquo/assets/20624652/f7ff3b83-86d7-4d58-bc6d-f17aeb9cf473)
![image](https://github.com/RHSMODS/statusquo/assets/20624652/8a8fea2c-0f04-441b-b981-0e4370729b90)

Vests themselves do not typically provide storage space for gadgets, tools, or magazines. The storage space is provided by attached pouches that can be customized based on the user's needs. However, plate carriers are designed specifically to carry protective plates for customized protection. Some vests may have built-in pouches that offer additional storage space alongside other attachment points.

### **Example of attachment to modular Vests and Plate Carrier**

**Magazine Pouches:** These pouches securely hold and carry extra magazines for firearms. it provide player for slots that can carries only certain magazines enable player to reload faster that magazine that in generic pouches and back bags. Additionally, to provide visual cues for supply status, it would be beneficial if the game incorporates the visibility of magazines in pouches, indicating whether they are empty or still contain magazines . This feature can offer players and those around them valuable information about the current ammunition availability in a more immersive and intuitive manner (as shown in below image).

![image](https://github.com/RHSMODS/statusquo/assets/20624652/9a9ddbf1-fcc8-4979-bedc-02c305a6f041)

**Utility Pouches:** Versatile storage options for items like multitools, first aid supplies, communication devices, or other small equipment. it provide player slots that can carries almost anything and player can access them quicker than back bags.

![image](https://github.com/RHSMODS/statusquo/assets/20624652/a257d46c-ff50-405e-bb39-b0c00eb23bda)

**Admin Pouches:** Multiple compartments and organizers to store administrative items like pens, notepads, maps, identification cards, and personal belongings. it provide player for slots that can carries only maps ,papers ,documents , map tools and notepads and player can access them quicker than back bags 

**Grenade Pouches:** Specifically designed to securely hold and provide quick access to grenades or similar explosive devices. it provide player for slots that can hold only grenades or similar explosive devices and provide quick access to grenades and player can access them quicker than back bags 
![image](https://github.com/RHSMODS/statusquo/assets/20624652/cf51b273-0afb-42d0-9757-d4b82543e393)

**Radio Pouches:** Used to carry communication devices such as handheld radios enabling player quicker use radio other than if the radio in other pouch or back bag.
![image](https://github.com/RHSMODS/statusquo/assets/20624652/408117e4-4902-4fdd-8fb0-b02b175d2457)

**Tool/Specialized Pouches:** Carry and organize various tools needed for battlefield such as repair tool kit pouch,  drone kit pouch or BuddyStrap Injured Person Carrier pouch .

**Medical Pouches :** Carry and organize various medical kit and supplies and come in various sizes , it provide player for slots that can hold only medical devices and supplies in organized manner to help player reach those items quicker than back bags and generic pouches.
![image](https://github.com/RHSMODS/statusquo/assets/20624652/0a8ec097-2979-4925-a2b3-884a1b0c66f0)

**Tactical Vest Phone/tablet Holder:** Securely holds and provides quick access to a mobile phone or tablet while wearing a tactical vest, enabling player to use phones/tablets/devices quickly without holding it in hands and also provide the player the ability to pin the device screen on the gameplay UI . (like microdagr in arma 3 ACE mod)
![image](https://github.com/RHSMODS/statusquo/assets/20624652/b84dbdee-0148-4513-8d24-fe0684ea2d90)
![image](https://github.com/RHSMODS/statusquo/assets/20624652/48162927-cdba-4567-a403-94a2eeddb228)

**Flashlight pouches** are designed to securely hold and provide quick access to flashlights during low-light or nighttime operations. They also offer the ability to switch on certain types of flashlights to illuminate the area in front of the player.
![image](https://github.com/RHSMODS/statusquo/assets/20624652/520ae839-69c5-4811-9141-07738053fbc8)

**Pistol/ Holster Pouch:** Securely holds a pistol or handgun for quick and convenient access.
![image](https://github.com/RHSMODS/statusquo/assets/20624652/1dbfa4bb-8bfc-498b-9000-88fb4b649aff)

**Patches and insignias :** Vest patches and flags can be added for identification or personalization.
![image](https://github.com/RHSMODS/statusquo/assets/20624652/48225253-c77c-4d46-adbd-6e00ceea1c48)

**Extra armor vests** can be equipped with additional armor attachments, such as an Armored Cummerbund, which provides extra protection for other body parts beyond the vest itself. This attachment enhances the overall armor coverage and improves the wearer's defensive capabilities in combat situations.
![image](https://github.com/RHSMODS/statusquo/assets/20624652/69947602-0250-4dda-b1d3-a95b52f6fba8)

### **Modding Framework**

Modders have the ability to introduce single vests/plate carriers in the game that can implement either new or existing attachment modular systems. These vests can also feature custom attachment points that are specific to that particular vest, allowing for unique customization options.

Furthermore, these vests may come with built-in functions or features that are exclusive to them. These built-in functions can provide additional utility or advantages, enhancing the overall gameplay experience.

By incorporating both existing and custom attachment systems, as well as built-in features, modders can provide a diverse range of vest options for players to explore and customize. This level of modding flexibility allows for extensive customization possibilities, enriching the game with unique vest variations.

Modders have the capability to define attachments that are specific to certain vest mount points or attachment systems. These attachment systems are typically structured as a grid of points, with each attachment defined to attach to a specific configuration of points, such as 1x1, 2x2, 3x2, and so on. The total space available on the grid will vary based on the design and size of the vest itself.

For example, a vest may have a grid size of 6x10, providing a total of 60 attachment points for modders to work with. They can then define attachments that align with this grid, allowing players to customize their loadouts by attaching different gear, pouches, or accessories to the available mount points on the vest.

This level of customization and compatibility with specific attachment systems and mount points allows modders to create a wide range of options for players to personalize their vests and tailor them to their specific needs and preferences in the game.

Modders also have the ability to assign unique functions to each attachment. For example, an attachment can consist of a larger pouch that can hold generic items, with an additional two smaller pouches specifically designed to carry magazines. This allows players to have versatile storage options, where they can store various items in the larger pouch while conveniently keeping their magazines readily accessible in the dedicated magazine pouches. This level of customization enables players to tailor their loadouts and optimize their equipment for specific gameplay situations.

Modders have the flexibility to define specific conditions, requirements, and processes for installing, replacing, or removing each attachment or part in the game. This allows for a more immersive and realistic gameplay experience, as players may need to meet certain criteria or follow specific steps to modify their vests.

Below Example of a vest that does not follow any attachment system but it comes with built-in storage space in form of pouches and pockets with one vest specific  attachment point that can accommodate Patch/insignia/nametag attachment.
![image](https://github.com/RHSMODS/statusquo/assets/20624652/644be446-319c-44a7-a385-a87016c7f80a)

Below Example of real life vests attachments 
![image](https://github.com/RHSMODS/statusquo/assets/20624652/ac8e92da-f1f2-4bbc-a18d-931292fcbdbf)
![image](https://github.com/RHSMODS/statusquo/assets/20624652/f6faa613-7306-47fd-a2ba-274ca53f6943)
![image](https://github.com/RHSMODS/statusquo/assets/20624652/6baca99f-02e4-4bef-9aae-db4e175e7761)

**Comment by ajvorobiev** [comment]
Not planned at the moment. A bit too hardcore. Its already a bit hard to find a good balance between gameplay and realism. Thanks anyway for the time you spent for the detail description. We'll keep it archived for the future maybe.
