### ISSUE TITLE
ECH

### ISSUE THREAD

**Issue by gurdyboy** [RHSMODS/statusquo#59]
Phase 1
- [x] High-cut shell @gurdyboy 
- [x] High-cut suspension system @gurdyboy 
- [x] Low-cut shell @gurdyboy 
- [ ] Low-cut suspension system @gurdyboy 
- [x] USMC one-hole mounting bracket @ajvorobiev 
- [x] ARC skeleton shroud for MICH @ajvorobiev 
- [x] Reversible MARPAT helmet cover

Phase X
- [ ] Army suspension system @gurdyboy 
- [ ] Army OEF-CP & OCP helmet cover

**Comment by ajvorobiev** [comment]
Helmet covers will move to own tasks.
