### ISSUE TITLE
RPG-7 PGO7V3 reticle

### ISSUE THREAD

**Issue by drklotos** [RHSMODS/statusquo#622]
Hello. Problem with the RPG-7 PGO7V3 sight. It is not valid for the game. Proof on video. The reticle shown in the screenshot is more suitable. Taken from the game SQUAD

https://imgur.com/a/FwpLnH0

https://youtu.be/Pfbh6ZEOLrU

**Comment by reyhard** [comment]
reticle from squad is completely wrong 
![obraz](https://github.com/RHSMODS/statusquo/assets/9433406/38872394-a4a6-49fd-b3a0-ef07fb559d0a)
OG-7 is using following lines. In any case, ballistic of rockets is not set yet, so the problem is not reticle but rocket configuration

**Comment by ajvorobiev** [comment]
Yes I agree. You can see that the VM (which is the vanilla one) has more or less good arc for the sight. VR and the rest of the new rockets are not zeroed in correctly. The sight itself is correct (layout, markings, distances, fov and size estimation) as it was traced from the real thing.
