### ISSUE TITLE
Killpatches/ Flags float on Crye G3 Shirt

### ISSUE THREAD

**Issue by TokaiTeio6104** [RHSMODS/statusquo#645]
Patches float when holding weapon
![Floaty McFloatPatch 2](https://github.com/RHSMODS/statusquo/assets/138264098/2e1bb42b-47cd-476d-a908-217ff6d4be44)
![Floaty McFloatPatch 1](https://github.com/RHSMODS/statusquo/assets/138264098/8d37afd7-c2fb-447c-88b1-15c9d053fa97)

**Comment by ajvorobiev** [comment]
Its better now but impossible to get rid of the floating completely unfortunately.
