### ISSUE TITLE
Separate rail covers into single piece per prefab

### ISSUE THREAD

**Issue by odkupiciel375** [RHSMODS/statusquo#650]
Change rail cover prefabs so they dont contain multiple rails in one prefab:
- add separate slot to wapons for top and side attachments
- change either short or long rail cover attachment type to prevent attaching long rail covers to M4 as they dont fit
- one rail cover entity can conver only one rail (not 2 or 3)
- adjust position of rail cover model to have common point with other attachments like f.e.: ANPEQ16 so they wont need special offsets

**Comment by ajvorobiev** [comment]
I refactored this. I think we cant get away with separate slots, only kits per type.
