### ISSUE TITLE
too long names for mags

### ISSUE THREAD

**Issue by odkupiciel375** [RHSMODS/statusquo#663]
![image](https://github.com/RHSMODS/statusquo/assets/19805800/67a01255-bf43-478d-89bd-33cf65a8661b)
https://enfusionengine.com/api/redirect?to=enfusion://ResourceManager/~RHSStatusQuo:Prefabs/Weapons/Magazines/Pmag/Magazine_556x45_PmagWindowed_30rnd_M855A1_last5tracer.et

![image](https://github.com/RHSMODS/statusquo/assets/19805800/ef2cde6e-1f77-4faf-96f2-93cc09dbd9db)
https://enfusionengine.com/api/redirect?to=enfusion://ResourceManager/~RHSStatusQuo:Prefabs/Weapons/Magazines/PmagUnwindowed/Magazine_556x45_PMAG_30rnd_M855A1_last5tracer.et

![image](https://github.com/RHSMODS/statusquo/assets/19805800/35651edf-c065-4891-aeac-ba1a30739f95)
https://enfusionengine.com/api/redirect?to=enfusion://ResourceManager/~RHSStatusQuo:Prefabs/Weapons/Magazines/Magazine_556x45_STANAG_HP_B_30rnd_M855A1_last5tracer.et

**Comment by gurdyboy** [comment]
removed caliber prefix from mag naming convention
