### ISSUE TITLE
Confirm storage components still work (mags, pouches, inspection etc.)

### ISSUE THREAD

**Issue by ajvorobiev** [RHSMODS/statusquo#680]

**Comment by Pnuky** [comment]
While accessing radial menu.

WORLD        : UpdateEntities
 WORLD        : FixedFrame
  SCRIPT    (E): Virtual Machine Exception

Reason: Index out of bounds.

Class:      'SCR_ResourceSystem'
Function: 'Get'
Stack trace:
Scripts/Game/Systems/SCR_ResourceSystem.c:40 Function OnUpdate
  SCRIPT    (E): Virtual Machine Exception

Reason: Index out of bounds.

Class:      'SCR_ResourceSystem'
Function: 'Get'
Stack trace:
Scripts/Game/Systems/SCR_ResourceSystem.c:40 Function OnUpdate
WORLD        : UpdateEntities
 WORLD        : PostFrame
  INPUT     (E): InputManager: unknown key 'keyboard:KC_ADD | keyboard:KC_SUBTRACT | keyboard:KC_LMENU'
WORLD        : UpdateEntities
 WORLD        : PostFrame
  INPUT     (E): InputManager: unknown key 'keyboard:KC_ADD | keyboard:KC_SUBTRACT | keyboard:KC_LMENU'
GUI       (E): ImageWidget::LoadImageFromSet: can't find image '' from ImageSet 'UI/Textures/Icons/icons_wrapperUI.imageset'
GUI       (E): ImageWidget::LoadImageFromSet: can't find image '' from ImageSet 'UI/Textures/Icons/icons_wrapperUI.imageset'
GUI       (E): ImageWidget::LoadImageFromSet: can't find image '' from ImageSet 'UI/Textures/Icons/icons_wrapperUI.imageset'
INIT         : Workbench Reload Game

**Comment by Pnuky** [comment]
![obraz](https://github.com/RHSMODS/statusquo/assets/16953449/53ff3b3b-9df3-46c1-89b1-efaa8356824c)
Custom keybind does not work, RMB as well.

**Comment by Pnuky** [comment]
Attachment system for wearable works.
Magazines being placed correctly in slots.

![obraz](https://github.com/RHSMODS/statusquo/assets/16953449/2556ede9-bd84-4cf3-a667-2dcb0cb1232d)
![obraz](https://github.com/RHSMODS/statusquo/assets/16953449/fe41e9ea-0505-47fb-8847-b2aace1f2e45)
![obraz](https://github.com/RHSMODS/statusquo/assets/16953449/90cd4a23-f5ae-42b0-aa35-cda217284eac)
![obraz](https://github.com/RHSMODS/statusquo/assets/16953449/46e708b9-d130-4dbd-8750-9df193aaa38a)
