### ISSUE TITLE
Навигатор Орион имеет не корректное исполнение интерфейса. 

### ISSUE THREAD

**Issue by LittleDrongo** [RHSMODS/statusquo#708]
1. Оси координат перепутаны местами.
2. В координатах указаны дециметры, а не метры.
[Пруф](https://www.youtube.com/watch?v=0ruyK3I3Fho)
Обратите внимание, ВС РФ не использует WSG84 , используется СК42.

![screen-1](https://github.com/RHSMODS/statusquo/assets/67188625/65bb0456-192b-424c-aca9-a0df3100778b)
![screen-2](https://github.com/RHSMODS/statusquo/assets/67188625/1d5dbcbe-1ae5-4c8d-8e5c-de9956fd8b8e)
![screen-3](https://github.com/RHSMODS/statusquo/assets/67188625/06719068-7493-441b-9abe-40293a6762dc)

**Comment by ajvorobiev** [comment]
Эта имплементация умышленная. Мы попытались сделать универсальный дисплей координат более подходящий для использования в игре для игроков всех сторон чтоб не путать особо. Спасибо за информацию, но пока оставим так.
