### ISSUE TITLE
Items stored in RHS pouch system have no cost in spawn in campaign gamemode

### ISSUE THREAD

**Issue by tacticaltoxic** [RHSMODS/statusquo#725]
repro:
1. load into conflict server with rhs
2. spawn as usmc guy
3. place something that costs money in pouches in pc gen3
4. save your loadout and kys
5. check your loadout price

**Comment by odkupiciel375** [comment]
probably SCR_InventoryStorageManagerComponent.GetAllRootItems() is not returning them
