### ISSUE TITLE
Acog Prone

### ISSUE THREAD

**Issue by Thunder311** [RHSMODS/statusquo#743]
Yesterday during operations I used the M27 suppressed with Acog. At times while in prone ads would present a black screen. Transition to kneeling and sight picture would appear. Move to probe sight picture would revert to black screen. Noticed this issue as well with the elcan.

**Comment by odkupiciel375** [comment]
Issue visualisation and repro:
https://www.youtube.com/watch?v=SkpObv0atac
1) Equip rifle with acog
2) go prone
3) ads
4) turn around => at some point camera clips through the render target of that scope

*this issue is also present on vanilla 1P29 but PSO1 as well as ATRII dont have such issue

**Comment by odkupiciel375** [comment]
cannot reproduce this anymore in 1.2
