### ISSUE TITLE
PC Gen 3 could have second velcro slot

### ISSUE THREAD

**Issue by screech169619** [RHSMODS/statusquo#751]
![5f57e6f8-cea5-43bf-aaa1-9a4748641fb6](https://github.com/RHSMODS/statusquo/assets/167607723/5029f58b-802c-4f90-9a8e-18131b8c29b1)

**Comment by screech169619** [comment]
it is impossible to place a velcro patch on the top velcro spot

**Comment by odkupiciel375** [comment]
rn it only has one slot, but technically we could add second one to the top part

**Comment by screech169619** [comment]
odkupiciel thanks for changing the title I could not come up with anything else lol💀💀
