### ISSUE TITLE
Vehicles

### ISSUE THREAD

**Issue by Cdeb123** [RHSMODS/statusquo#773]
All RHS scenarios (campaign and MP) have a bug right now. 

When you go to spawn RHS Vehicles they do not appear and are not able to be spawned no matter what.

I have tested and you cannot spawn *any* vehicles even base vehicles through game master.

Since RHS replaces base vehicles we are not able to spawn vehicles through the Heavy or Light debot areas. 

I am not sure if this bug is happening to all people but I just installed a fresh install of my server and it is currently happening.

Campaign I get two humvees and a supply truck on MP I don't get anything.

Arland RHS scenario and Everon both have the same issue.

**Comment by ajvorobiev** [comment]
Duplicate
