### ISSUE TITLE
Minor clipping on the hoodie when holding a weapon 

### ISSUE THREAD

**Issue by CrypticUnseen** [RHSMODS/statusquo#802]
![88c164f2-947e-466f-ad5d-69cf7dce921e](https://github.com/RHSMODS/statusquo/assets/164115936/8f12138e-a08f-4e95-80b0-6a3476f5c84f)
![b1783c59-3cb0-4bc4-812a-7df4b0e3d0d6](https://github.com/RHSMODS/statusquo/assets/164115936/185368c3-94ff-4b1c-9465-912175d1883e)
![47de64fb-4bda-4cda-8706-7c9e05e6347c](https://github.com/RHSMODS/statusquo/assets/164115936/07d4d0c9-9b6d-47a4-856d-b8a851b1ce31)
![13b3e639-1d5e-4999-b008-be3e6a49bd0c](https://github.com/RHSMODS/statusquo/assets/164115936/4f30728d-52ce-4f06-b899-280742849cbf)
![bcb82c82-ddf8-4090-9d58-597903930dc8](https://github.com/RHSMODS/statusquo/assets/164115936/4efff8fc-42f3-44bf-9963-b2c99aacf380)

**Comment by Vergyy** [comment]
fixed.
