### ISSUE TITLE
MICH 2000 with shroud and Velcro has no slots for strobe or battery pack 

### ISSUE THREAD

**Issue by Canadianrebel05** [RHSMODS/statusquo#803]
The Mich 2000 with the shroud and Velcro has no attach points for a strobe or battery pack 

![3b27b595-5bf1-4065-a19e-6671dd9410d1](https://github.com/RHSMODS/statusquo/assets/170839149/395a55a3-2f88-4385-8f77-66153a7b66ac)
![5815a9e7-7b67-475c-b262-beee326a08c7](https://github.com/RHSMODS/statusquo/assets/170839149/f610d102-50a9-414a-b784-6003cf146181)
![f19e891d-6de3-4e50-87a4-2d781d149760](https://github.com/RHSMODS/statusquo/assets/170839149/d42048c6-3ee7-47b1-9946-62770f61cea1)
![be6d0dfb-fba0-487e-86ed-112b97c260d8](https://github.com/RHSMODS/statusquo/assets/170839149/fb593f46-32c4-41d2-9d1e-4d0b7048d6c7)
![c4fb58dd-baf4-4706-8cc1-39b83427a37e](https://github.com/RHSMODS/statusquo/assets/170839149/77c17c39-5559-43e5-9f8c-6c8052a43850)

In most pictures I could find of the helmet troops or manufactures have Velcro either on the back or top for a strobe to be mounted
![IMG_6780](https://github.com/RHSMODS/statusquo/assets/170839149/85d91452-030b-43fb-9aab-e6edcade832b)
![IMG_6776](https://github.com/RHSMODS/statusquo/assets/170839149/5e15d667-0799-414d-8ce5-596a12621f78)
![IMG_6775](https://github.com/RHSMODS/statusquo/assets/170839149/8797e1e5-406f-42ec-8ded-929620cf5d3b)
![IMG_6767](https://github.com/RHSMODS/statusquo/assets/170839149/a5e32c14-8be0-47a7-ac40-14e2689c2c84)
![IMG_6768](https://github.com/RHSMODS/statusquo/assets/170839149/fd9a5838-1a4e-4a3e-8675-d098abf3ecb2)

Sorry for any inconvenience this causes

**Comment by Canadianrebel05** [comment]
Forgot to post a shot of which helmet it is from the box so here ya go
![Uploading c4fb58dd-baf4-4706-8cc1-39b83427a37e.png…]()

**Comment by Canadianrebel05** [comment]
To be completely honest I’m not sure exactly what would need to be done to add some more Velcro attach points but I know that it would make the helmet a lot more functional and make the model look even better

**Comment by ajvorobiev** [comment]
Not planned
