### ISSUE TITLE
M4 CQBR Block II

### ISSUE THREAD

**Issue by ruzmac** [RHSMODS/statusquo#807]
Issue where there is a separate optic view on the front of the suppressor - by this I mean when you toggle between optics there is an additional one on the front of the suppressor/weapon

**Comment by da12thMonkey** [comment]
From testing, the issue appears to be caused by the presence of the MBUS front sight attachment rather than the rifle itself.
It affects the CQBR Block II prefabs both with and without suppressor.
Removing the front sight removes this problem optic mode.
