### ISSUE TITLE
Weird bending at the elbow for rifle animation pose

### ISSUE THREAD

**Issue by Vergyy** [RHSMODS/statusquo#808]
![image](https://github.com/RHSMODS/statusquo/assets/107449389/547a73c9-4a69-4a76-8c51-f13109ae2bd2)
![image](https://github.com/RHSMODS/statusquo/assets/107449389/2677a538-983d-4468-9b80-b7ece8afd4bc)

**Comment by ajvorobiev** [comment]
Duplicate of #779
