### ISSUE TITLE
(1.2) Vanilla ARTII scope throws error

### ISSUE THREAD

**Issue by Cyborgmatt** [RHSMODS/statusquo#817]
1. Equip the vanilla `Prefabs/Weapons/Rifles/M14/Rifle_M21_ARTII.et` prefab, aka the M21, with pre-slotted ARTII scope
2. Aim down the sight, and this error will be thrown:

![image](https://github.com/RHSMODS/statusquo/assets/3114217/8149b7db-830a-4c92-950e-11a933779912)

**Comment by ajvorobiev** [comment]
good find!
