### ISSUE TITLE
nvg is visible on  0 0 0 on character when placed in backpack via workbench

### ISSUE THREAD

**Issue by tacticaltoxic** [RHSMODS/statusquo#820]

**Comment by ajvorobiev** [comment]
is this not the age old AR bug?

**Comment by ajvorobiev** [comment]
how?
![image](https://github.com/RHSMODS/statusquo/assets/7216776/2caed446-3c5a-4385-ab6c-eb7542e683dc)

**Comment by ajvorobiev** [comment]
And then what its visible in inventory at 0 0 0 or in 1st/3rd person view? Why u write that you have reproduction steps and then do not write clear steps?

**Comment by benjibossk** [comment]
i dont know if it help but we have the same trouble with weapon
![image](https://github.com/RHSMODS/statusquo/assets/27146048/a2918e6c-481b-4b79-a855-bdfe81e422a8)

**Comment by ajvorobiev** [comment]
This gotta be vanilla bug.
