### ISSUE TITLE
(1.2) Light device mode not working in 1.2 expiremental 

### ISSUE THREAD

**Issue by pniyxbox** [RHSMODS/statusquo#827]
![06D4B177-03EB-47FA-A5B4-0FDA7B665C36](https://github.com/RHSMODS/statusquo/assets/173402575/9a3ada61-2733-4c03-801c-43573254fa5a)

Toggle Light Device, Cycle Through Light Device Modes, and Momentarily Turn ON Light Device functions don’t seem to work, even tried unbinding all other controls and rebinding the ones not working and still nothing.

After more testing it seems to be a problem with the pre built rifles that come with the PEQ16 already on them because when you take the peq itself from the box and attach it the controls all work.

**Comment by odkupiciel375** [comment]
thos shortcuts broke in general
