### ISSUE TITLE
Ms2000 and mohoc

### ISSUE THREAD

**Issue by Phantom9062** [RHSMODS/statusquo#835]
Not really an issue but the MS2K and the mohoc should be mountable on the side of the helmet not just the back and top like the pictures attached 
![images](https://github.com/RHSMODS/statusquo/assets/173753437/a2013d16-22dc-4b58-a954-a11669c13ce7)
![mohoc_3_large-510x382](https://github.com/RHSMODS/statusquo/assets/173753437/22d78c8a-07bc-48e5-b372-9b05ff86e55b)

**Comment by ajvorobiev** [comment]
this would require a lot of rework. Will not do.
