### ISSUE TITLE
(1.2) 6 Rib Rail Cover detach string

### ISSUE THREAD

**Issue by Cyborgmatt** [RHSMODS/statusquo#836]
The 6 Rib Rail Cover is missing its detach string.

![image](https://github.com/RHSMODS/statusquo/assets/3114217/9a7d5b29-5a4c-4d6d-b92e-a6015829c50d)

**Comment by odkupiciel375** [comment]
duplicate of https://github.com/RHSMODS/statusquo/issues/738
