### ISSUE TITLE
Saving with RHS NVGS (any) causes server crash

### ISSUE THREAD

**Issue by emirtal** [RHSMODS/statusquo#849]
Saving with Vanilla or Bacon with NVGs equipped leads to server crash: 

- Replicated multiple times
------------------------------------------------------------------------------------------------------------

27.06 2024 11:25:57
Unhandled exception

Program: /home/user/.local/share/Steam/armar_ds/ArmaReforgerServer
Reason: Unknown

------------------------------------
Class:      'SCR_ArsenalManagerComponent'
Function: 'WriteValue'
Stack trace:
scripts/Game/GameMode/Loadout/SCR_ArsenalManagerComponent.c:964 Function SetPlayerArsenalLoadout
scripts/Game/UserActions/SCR_SaveArsenalLoadoutAction.c:181 Function PerformAction

27.06 2024 11:05:18
Unhandled exception

Program: /home/user/.local/share/Steam/armar_ds/ArmaReforgerServer
Reason: Unknown

Class:      'Bacon_GunBuilder_PlayerFactionLoadoutStorage'
Function: 'WriteValue'
Stack trace:
scripts/Game/BaconLoadoutEditor/Bacon_GunBuilder_LoadoutStorage.c:24 Function SerializeCharacter
scripts/Game/BaconLoadoutEditor/Bacon_GunBuilder_LoadoutStorage.c:139 Function SaveLoadout
scripts/Game/BaconLoadoutEditor/Bacon_GunBuilder_LoadoutStorage.c:238 Function SaveCurrentPlayerLoadout
scripts/Game/BaconLoadoutEditor/M4Test_GunBuilder_PCComponent.c:469 Function Action_SavePlayerLoadout
scripts/Game/BaconLoadoutEditor/M4Test_GunBuilder_PCComponent.c:376 Function RpcAsk_RequestLoadoutAction

------------------------------------
27.06 2024 10:54:43
Unhandled exception

Program: /home/user/.local/share/Steam/armar_ds/ArmaReforgerServer
Reason: Unknown

Class:      'SCR_ArsenalManagerComponent'
Function: 'WriteValue'
Stack trace:
scripts/Game/GameMode/Loadout/SCR_ArsenalManagerComponent.c:964 Function SetPlayerArsenalLoadout
scripts/Game/UserActions/SCR_SaveArsenalLoadoutAction.c:181 Function PerformAction

------------------------------------
27.06 2024 10:45:06
Unhandled exception

Program: /home/user/.local/share/Steam/armar_ds/ArmaReforgerServer
Reason: Unknown

Class:      'Bacon_GunBuilder_PlayerFactionLoadoutStorage'
Function: 'WriteValue'
Stack trace:
scripts/Game/BaconLoadoutEditor/Bacon_GunBuilder_LoadoutStorage.c:24 Function SerializeCharacter
scripts/Game/BaconLoadoutEditor/Bacon_GunBuilder_LoadoutStorage.c:139 Function SaveLoadout
scripts/Game/BaconLoadoutEditor/Bacon_GunBuilder_LoadoutStorage.c:238 Function SaveCurrentPlayerLoadout
scripts/Game/BaconLoadoutEditor/M4Test_GunBuilder_PCComponent.c:469 Function Action_SavePlayerLoadout
scripts/Game/BaconLoadoutEditor/M4Test_GunBuilder_PCComponent.c:376 Function RpcAsk_RequestLoadoutAction

**Comment by ice19942335** [comment]
Simular issue!

Virtual Machine Exception
Reason: NULL pointer to instance

Class:      'SCR_HUDManagerLayoutHandler'
Function: 'StartMainLayout'
Stack trace:
Scripts/Game/UI/HUD/Handlers/HudManager/SCR_HUDManagerLayoutHandler.c:325 Function StartMainLayout
Scripts/Game/UI/HUD/Handlers/HudManager/SCR_HUDManagerLayoutHandler.c:341 Function OnUpdate
Scripts/Game/UI/HUD/SCR_HUDManagerComponent.c:150 Function OnUpdate
