### ISSUE TITLE
TV-110 Rigs cannot change arsenal via entity catalog modifications.

### ISSUE THREAD

**Issue by wik3dneverbroke** [RHSMODS/statusquo#852]

**Comment by wik3dneverbroke** [comment]
> what?

I am trying to move the TV-110MC rig and pouches to US team.
even when completely removing the rig from entity catalog it still appears in rus box and only rus box

**Comment by ajvorobiev** [comment]
Sorry this is not a RHS bug. We dont really give support for other mods here, perhaps you ca ask in the Reforger discord #enfusion_configuration to get some help.
