### ISSUE TITLE
Additional prefabs with RplComponent Errors

### ISSUE THREAD

**Issue by Cyborgmatt** [RHSMODS/statusquo#858]
`"Parent Node From Parent Entity" property on RplComponent of the item is set to true. It should be set to false.`

- `{E96622207AEB6376}Prefabs/Characters/HeadGear/Helmet_TOR2/TOR2_FaceShield.et`
- `{B1798B0F1258B765}Prefabs/Items/Equipment/Navigation/DAGR/DAGR.et`
- `{A55A815F28739FEC}Prefabs/Items/Equipment/Navigation/Orion/Orion.et`
- `{FE29640EBEEBC731}Prefabs/Weapons/Attachments/Misc/manta_railcover/manta_M27_kit1_blk.et`

**Comment by Cyborgmatt** [comment]
This needs to be flagged as a high-severity issue, as any prefab with this error can crash the server and cause mass disconnections to anyone in the same RPL bubble.

Also, these base prefabs need addressing as well as:

`{CA7E385AF38856D9}Prefabs/Weapons/Attachments/Handguards/Handguard_AK74M/Handguard_AK74M_base.et`
`{9C86BA57C1B1BE03}Prefabs/Characters/Vests/Vest_Taktika/Variants/Vest_Taktika_preset_base.et`
`{5E07E121D9688C2F}Prefabs/Characters/Vests/Vest_TV110/Variants/Vest_TV110_preset_base.et`
`{E96622207AEB6376}Prefabs/Characters/HeadGear/Helmet_TOR2/TOR2_FaceShield.et`

**Comment by Cyborgmatt** [comment]
Couple more:

`{B684CBB65C9C2628}Prefabs/Characters/Uniforms/VKPO/Undershirt_VKPO_attachable_base.et`
`{D901305DD97960AD}Prefabs/Weapons/Attachments/Misc/AkGpButtPad/akGPbutt.et`

**Comment by da12thMonkey** [comment]
Fixed the ones you've noted so far. Let me know if there are others.
I am having a check through stuff myself, but it's slow going
