### ISSUE TITLE
REAP-IR gain broken when looking south-ish in RHS Dev showcase scenario?

### ISSUE THREAD

**Issue by arolypoly** [RHSMODS/statusquo#863]
![image](https://github.com/RHSMODS/statusquo/assets/10502646/ffb4e787-289e-4f6f-88a1-7fee9a7b93d7)
RIP my eyes.
![image](https://github.com/RHSMODS/statusquo/assets/10502646/ab146eff-f71a-4c92-8ce2-1911290e6abf)
The direction I was looking.
![image](https://github.com/RHSMODS/statusquo/assets/10502646/466845b2-f538-4c56-8697-cf4f01d5d3b2)
What it looks like normally.

**Comment by arolypoly** [comment]
![image](https://github.com/RHSMODS/statusquo/assets/10502646/84c17a7b-2a63-45f5-b1a6-4fde7b115315)
There's also this, but this is with a bunch of other mods.

**Comment by ajvorobiev** [comment]
This is likely because of the hacky implementation. Until proper support for IR in the engine there is not much we can do.
