### ISSUE TITLE
kh-55 and Gbu-12 strike 

### ISSUE THREAD

**Issue by drPanda1893** [RHSMODS/statusquo#873]
When plaing it the explosion effect isnt playing + no sound but the animation from the plane and bomb is working.

Class: 'RHS_CAS_EditableEntityComponent'
Function: 'RPC_DoTrigger'
Stack trace:
scripts/Game/Editor/Components/EditableEntity/RHS_CAS_EditableEntityComponent.c:77 Function RPC_DoTrigger
scripts/Game/game.c:927 Function OnUpdate

**Comment by breadnbutter968** [comment]
Had a similar issue with the Kh-55. Each time one was spawned this error popped up, eventually led to server crash.
`22:15:17.841 WORLD        : UpdateEntities
22:15:17.841  RPL          : rpl::Pip::ProcessNetToGame
22:15:17.841   ENTITY       : SpawnEntityPrefab @"{17B08DA4B050BBFE}Prefabs/Vehicles/Missles/kh55/KH55_CAS.et"
22:15:17.841    WORLD        : InitEntities 'world'
22:15:17.841     ENTITY       : Init entity @"ENTITY:4611686018427390101" ('GenericEntity','Assets/Vehicles/Missles/kh55/kh55.xob') at <4783.140137 24.740936 11980.632812> @"{17B08DA4B050BBFE}Prefabs/Vehicles/Missles/kh55/KH55_CAS.et"
22:15:17.841      RPL       (E): IReplication::InsertNodeError: Attempting to register one item from multiple RplNodes! This is a critical failure and should be brought to attention and resolved IMMEDIATELY! itemId=0x800018E8 name=SignalsManagerComponent node=Assets/Vehicles/Missles/kh55/kh55.xob current_node=Assets/Vehicles/Missles/kh55/kh55.xob, item=script::Game::SignalsManagerComponent, current_item=script::Game::SignalsManagerComponent
22:15:25.920 WORLD        : UpdateEntities
22:15:25.920  RPL          : rpl::Pip::ProcessGameToNet
22:15:25.920   ENGINE    (E): Application crashed! Generated memory dump: /tmp/a83fa5b8-4efc-4272-f87867a6-78e5cae4.dmp
22:15:25:969 CRASH REPORT : Crash reporter started!
22:15:25:969 CRASH REPORT : Started without dialog window! Automatically send Report.
22:15:25:969 CRASH REPORT : Sending analytical data.
22:15:25:969 CRASH REPORT : Sending Request...
22:15:26:900 CRASH REPORT : Crash Analytics: OK
22:15:26:906 CRASH REPORT : Preparing Report
22:15:26:907 CRASH REPORT : Memory dump Size: 55 kb
22:15:26:907 CRASH REPORT : Logs Size: 31 kb
22:15:26:907 CRASH REPORT : Sending Crash Report!
22:15:26:907 CRASH REPORT : Sending Request...
22:15:27:815 CRASH REPORT : Report Result: - SUCCESS - Crash GUID: 679adc51-3eb3-4000-8d02-95cf90b2d949
22:15:27:815 CRASH REPORT : Crash Reporter `Finished!``
