### ISSUE TITLE
Users game crash with NVG/helmet strobe

### ISSUE THREAD

**Issue by emirtal** [RHSMODS/statusquo#875]
Few users on our server are reporting complete game crashing when using the helmet Illuminator/strobe.

1.

------------------------------------
01.07 2024 21:00:25
Virtual Machine Exception

Reason: NULL pointer to instance. Variable '#return'

Class:      'RHS_NVGIlluminatorComponent'
Function: 'AttachLightToCamera'
Stack trace:
Scripts/Game/Components/Gadgets/RHS_HeadMountedLightDeviceComponent.c:33 Function AttachLightToCamera
Scripts/Game/Components/Gadgets/RHS_HeadMountedLightDeviceComponent.c:105 Function OnSlotChanged
Scripts/Game/generated/Components/InventorySystem/InventoryItemComponent.c:89 Function OnParentSlotChanged

Runtime mode

------------------------------------
01.07 2024 21:00:37
Virtual Machine Exception

Reason: NULL pointer to instance. Variable '#return'

Class:      'RHS_NVGIlluminatorComponent'
Function: 'AttachLightToCamera'
Stack trace:
Scripts/Game/Components/Gadgets/RHS_HeadMountedLightDeviceComponent.c:33 Function AttachLightToCamera
Scripts/Game/Components/Gadgets/RHS_HeadMountedLightDeviceComponent.c:105 Function OnSlotChanged
Scripts/Game/generated/Components/InventorySystem/InventoryItemComponent.c:89 Function OnParentSlotChanged

Runtime mode

------------------------------------
01.07 2024 21:04:39
Virtual Machine Exception

Reason: NULL pointer to instance. Variable '#return'

Class:      'RHS_HeadMountedLightDeviceComponent'
Function: 'AttachLightToCamera'
Stack trace:
Scripts/Game/Components/Gadgets/RHS_HeadMountedLightDeviceComponent.c:33 Function AttachLightToCamera
Scripts/Game/Components/Gadgets/RHS_HeadMountedLightDeviceComponent.c:105 Function OnSlotChanged
Scripts/Game/generated/Components/InventorySystem/InventoryItemComponent.c:89 Function OnParentSlotChanged

Runtime mode

------------------------------------
01.07 2024 21:04:39
Virtual Machine Exception

Reason: NULL pointer to instance. Variable '#return'

Class:      'RHS_NVGIlluminatorComponent'
Function: 'AttachLightToCamera'
Stack trace:
Scripts/Game/Components/Gadgets/RHS_HeadMountedLightDeviceComponent.c:33 Function AttachLightToCamera
Scripts/Game/Components/Gadgets/RHS_HeadMountedLightDeviceComponent.c:105 Function OnSlotChanged
Scripts/Game/generated/Components/InventorySystem/InventoryItemComponent.c:89 Function OnParentSlotChanged

Runtime mode

------------------------------------
01.07 2024 21:05:08
Unhandled exception

Program: E:\Steam\steamapps\common\Arma Reforger\ArmaReforgerSteam.exe
Reason: Access violation. Illegal read by 0x7ff736ec95fc at 0x59914468

SymGetSymFromAddr:487, addr:0x7ff736ec95fc
SymGetSymFromAddr:487, addr:0x7ff7369c5eae
SymGetSymFromAddr:487, addr:0x7ff7362cfbc7
SymGetSymFromAddr:487, addr:0x7ff736f34284
SymGetSymFromAddr:487, addr:0x7ff736f350fc
SymGetSymFromAddr:487, addr:0x7ff7362cca97
SymGetSymFromAddr:487, addr:0x7ff7371a3bd9
SymGetSymFromAddr:487, addr:0x7ff7371942e5
SymGetSymFromAddr:487, addr:0x7ff7371940e0
SymGetSymFromAddr:487, addr:0x7ff736275748
SymGetSymFromAddr:487, addr:0x7ff736274fb5
SymGetSymFromAddr:487, addr:0x7ff73768af76
[BaseThreadInitThunk]: ??? addr:0x7ffe4481257d
[RtlUserThreadStart]: ??? addr:0x7ffe45b8af28
[RtlUserThreadStart]: ??? addr:0x7ffe45b8af28

------------------------------------------------------------------------------------------------------------

2. 

------------------------------------
02.07 2024 00:41:15
Virtual Machine Exception

Reason: NULL pointer to instance. Variable '#return'

Class:      'RHS_NVGIlluminatorComponent'
Function: 'AttachLightToCamera'
Stack trace:
Scripts/Game/Components/Gadgets/RHS_HeadMountedLightDeviceComponent.c:33 Function AttachLightToCamera
Scripts/Game/Components/Gadgets/RHS_HeadMountedLightDeviceComponent.c:105 Function OnSlotChanged
Scripts/Game/generated/Components/InventorySystem/InventoryItemComponent.c:89 Function OnParentSlotChanged

Runtime mode

------------------------------------
02.07 2024 00:45:07
Unhandled exception

Program: E:\SteamLibrary\steamapps\common\Arma Reforger\ArmaReforgerSteam.exe
Reason: Access violation. Illegal read by 0x7ff69328733b at 0xffffffffffffffff

SymGetSymFromAddr:487, addr:0x7ff69328733b
SymGetSymFromAddr:487, addr:0x7ff693286919
SymGetSymFromAddr:487, addr:0x7ff692d1c490
SymGetSymFromAddr:487, addr:0x7ff692d1d08a
SymGetSymFromAddr:487, addr:0x7ff692d1e4bb
SymGetSymFromAddr:487, addr:0x7ff693284ba3
SymGetSymFromAddr:487, addr:0x7ff693286f1f
SymGetSymFromAddr:487, addr:0x7ff69328555a
SymGetSymFromAddr:487, addr:0x7ff69261ca97
SymGetSymFromAddr:487, addr:0x7ff6934f3bd9
SymGetSymFromAddr:487, addr:0x7ff6934e42e5
SymGetSymFromAddr:487, addr:0x7ff6934e40e0
SymGetSymFromAddr:487, addr:0x7ff6925c5748
SymGetSymFromAddr:487, addr:0x7ff6925c4fb5
SymGetSymFromAddr:487, addr:0x7ff6939daf76
[BaseThreadInitThunk]: ??? addr:0x7fff9d6f257d
[RtlUserThreadStart]: ??? addr:0x7fff9ef4af28
[RtlUserThreadStart]: ??? addr:0x7fff9ef4af28

Runtime mode

**Comment by odkupiciel375** [comment]
same as https://github.com/RHSMODS/statusquo/issues/861
