### ISSUE TITLE
RHS inventory overrides introduce already fixed bugs in vanilla.

### ISSUE THREAD

**Issue by The-Soviet-Peanut** [RHSMODS/statusquo#916]
There is a couple of bugs and atleast one feature that you guys override by your inventory script. Which then leads to those issues being reintroduced or new features missing.

From what I've noticed so far there are atleast two bugs reintrotruced:
- Occasional non refreshing UI on equipping things like binos from arsenal.
- Refunding items when you drag and drop them in the arsenal.

And atleast one new feature:
- Using F while hovering over items to equip them.

**Comment by The-Soviet-Peanut** [comment]
Correction. The binos bug is still present on stable. Ignore that part.

**Comment by Cyborgmatt** [comment]
This is also why gloves are not auto-equipped into the glove slot compared to vanilla.
