### ISSUE TITLE
Restrict GEO-ONV1-01 to be only be placeable on ZSh-7V

### ISSUE THREAD

**Issue by ajvorobiev** [RHSMODS/statusquo#918]
Right now the ZSh-7V is set up like all other helmets, accepts all NVG. Similarly GEO-ONV1-01 can also be mounted everywhere. We need to further refine the system so that certain mounts can only accept certain MVGs and vice versa. While I dont think we should fully restrict all helmets and shrounds with only compatible NVGs mounting brackets, I think cases like ZSh and eventually HGU can be examples where this can be an exception.

**Comment by odkupiciel375** [comment]
all that should be needed is custom LoadoutAreaType

**Comment by ajvorobiev** [comment]
> all that should be needed is custom LoadoutAreaType

Should there not be any other consideration for the scripts to function correctly?

**Comment by odkupiciel375** [comment]
no, all that was needed was new LoadoutAreaType - added RHS_LoadoutZShNVGlotArea and RHS_LoadoutHGUNVGlotArea (for the future) which are not compatible with generic RHS_LoadoutNVGSlotArea
