### ISSUE TITLE
K17 Client crash when destroyed by GM

### ISSUE THREAD

**Issue by M-Vinu** [RHSMODS/statusquo#923]
K17 sometimes causes a client crash when destroyed in MP
Steps to reproduce:
- Open GM interface
- Spawn Epoch or Berezok variants of K17
- Destroy the vehicle via GM

Notes:
Client does not seem to crash when destroying Bumerang variant.

- Crash GUID: b974c421-26e7-4d6c-ac1d-db20e3a131b4

Client console, error and crash logs (When destroying Berezok variant):
- [console.log](https://github.com/user-attachments/files/16289334/console.log)
- [crash.log](https://github.com/user-attachments/files/16289335/crash.log)
- [error.log](https://github.com/user-attachments/files/16289336/error.log)

Client console, error and crash logs (When destroying Epoch variant):
- [console.log](https://github.com/user-attachments/files/16289360/console.log)
- [crash.log](https://github.com/user-attachments/files/16289361/crash.log)
- [error.log](https://github.com/user-attachments/files/16289363/error.log)

Server console log:
- [crash_k17.txt](https://github.com/user-attachments/files/16289260/crash_k17.txt)

**Comment by JiraF4** [comment]
Finally found problem.
Should be fixed after next RHS update.
