### ISSUE TITLE
Clipping between Filbe and 6.11 backpacks and AVS, JPC and NCPC plate carriers when equipped

### ISSUE THREAD

**Issue by ruzmac** [RHSMODS/statusquo#943]

**Comment by ruzmac** [comment]
![image](https://github.com/user-attachments/assets/993397c1-5a44-4d82-834c-aec967350ca4)

![image](https://github.com/user-attachments/assets/e1dedf10-63d2-400d-b339-05ec182534fe)

**Comment by ajvorobiev** [comment]
Closed a while ago.
