### ISSUE TITLE
Balaclava clipping through ECH-HC and ECH-LC helmet straps since latest Stable update

### ISSUE THREAD

**Issue by AmbientMantis** [RHSMODS/statusquo#970]
![7db763f0-7713-4d33-9735-05a57f0976cb](https://github.com/user-attachments/assets/fbce68b4-ac15-40fd-b411-71f150dfa01a)
![22c48c05-18df-41f5-b197-acd8aaca85ad](https://github.com/user-attachments/assets/96cd4645-f6f7-4645-8ffb-7eea62fae00e)

**Comment by ajvorobiev** [comment]
not fixable, and not relevant for the future
