### ISSUE TITLE
[0.9.3326] NVGs stop working after respawn

### ISSUE THREAD

**Issue by Cyborgmatt** [RHSMODS/statusquo#974]
There appears to be an issue preventing the NVG keybind or the NVGs themselves from functioning properly after respawning with a saved loadout.

Steps to reproduce the issue:

1. Start an RHS conflict scenario and save a loadout that includes both a helmet and NVGs.
~~2. After respawning with the saved loadout, the NVGs will stop working until you drop and re-equip the entire helmet.~~
Update: 2. It appears the main issue revolves around dying when NVGs are active, upon respawning the NVG overlay will remain permanently on the screen.

Additionally, if you die while the NVGs are active and respawn with a saved loadout, the NVG HDR overlay will still be visible across the screen, but the mask itself will be missing.

![image](https://github.com/user-attachments/assets/6aec1656-a718-4d09-aaa1-8400802de8a8)

**Comment by ajvorobiev** [comment]
probably connected to #975
