### ISSUE TITLE
[0.9.3326] TA648MDO + RMR doesn't work in MP

### ISSUE THREAD

**Issue by Cyborgmatt** [RHSMODS/statusquo#977]
The new `{36EF773EB236A891}Prefabs/Weapons/Attachments/Optics/ta648mdo/Optic_TA648MDO_rmr.et` scope, which includes the RMR on top, doesn't function properly on servers. Instead, it spawns the base TA648MDO scope without the RMR attachment.

It works correctly in the workbench, so this seems to be an issue related to the server or RPL.

Steps to reproduce:

1. Join a server.
2. Spawn either a weapon with the Optic_TA648MDO_rmr.et attached or spawn the scope prefab itself.
3. You'll notice the RMR is missing from the mounted scope.

**Comment by Theplayer763** [comment]
Same thing happens in multiplayer to the IT-1TWS-315A (T1) the T1 is disconnected from the thermal unit and is unusable, I believe this also occurs to the new optics that have the AN/PAS-13G combined with it as well.
