### ISSUE TITLE
Rolled Crye G3s Clipping 

### ISSUE THREAD

**Issue by pniyxbox** [RHSMODS/statusquo#981]
![IMG_4090](https://github.com/user-attachments/assets/80b2b0fa-7fae-4f46-84f1-fb0f5ae61d3c)

**Comment by ajvorobiev** [comment]
not sure this is fixable

**Comment by pniyxbox** [comment]
> not sure this is fixable

that’s unfortunate, you can’t hide certain parts of the body mesh? i remember there used to be clipping issues with the frog pants and i believe that’s how they were fixed

**Comment by da12thMonkey** [comment]
You can hide certain parts, but the coverage of what can be hidden is pre-set.
Hiding anything below the elbow means hiding everything up to the wrist. So the guy would then have no arms - just a pair of hands floating in the air

**Comment by ajvorobiev** [comment]
as expected, not possible to fix. In normal operation not visible anyway.
