### ISSUE TITLE
Download size/speed on series s/x

### ISSUE THREAD

**Issue by Strangetamer856** [RHSMODS/statusquo#983]
It really shouldn't take 30 minutes to download an essential pack. either reduce the size or get reforger to download your shit faster

**Comment by gurdyboy** [comment]
We do not intend on reducing the size of the mod, nor do we have any control over download speeds on the Xbox Series S/X. Sorry.

**Comment by Strangetamer856** [comment]
It's cool, I mainly blame reformer cause it's ass I only reached out cause
yall are easier to contact.
