### ISSUE TITLE
Clipping issues Rugby Shirt

### ISSUE THREAD

**Issue by bitesrad** [RHSMODS/statusquo#986]
The rugby shirt has some clipping issues when subjected to rare vanilla animations. That is to say these issues only present themselves in fairly unique situations. I've identified two such situations: (1) _prone with a deployed bipod, using the maximum allowed angles_ and (2) _auto raise weapon when close to an obstacle_.  In all likelihood these two situations are not exhaustive, but they do a decent job of illustrating the issue. 

For testing I used the the RPK which is from the vanilla game I believe (but also found in the RHS arsenal). It is possible the issue is exacerbated/mitigated when using RHS specific custom weapons.

Attached are two screenshots highlighting the various clipping errors.
![20240915161348_1](https://github.com/user-attachments/assets/a581fe25-5ee4-4d0e-94a5-f68b4e8bb6d2)

![20240915161436_1](https://github.com/user-attachments/assets/bfadeac5-5d35-448b-b971-c8564202a18a)

As you can see the issue presents itself on the **upper arm/bicep** and **around the neck**, specifically the lower part of the back neck and the side close to the shoulder.

**Comment by Vergyy** [comment]
Done.
