### ISSUE TITLE
[0.10.3529] Broken firemode animations

### ISSUE THREAD

**Issue by Cyborgmatt** [RHSMODS/statusquo#992]
Several weapons no longer have functional fire mode player animations on the experimental branch.

AKS, AK74M, AK105, SR3M are all impacted from my testing so far.

**Comment by da12thMonkey** [comment]
Bolt doesn't move when firing either, last I checked.
The vanilla AKs were broke in the same way on the last couple of Exp vers, and IIRC we were waiting for info on what needed updating.

**Comment by da12thMonkey** [comment]
Yeah, it was in 1.2.1.76 or earlier that they were broke. I asked some of the BI guys if they knew about it at the time and they said it was a known issue that needed fixing - evidently in 1.2.1.86

We've already done the `GetEventTime("Reload.Erc.Reload_InsertMag", "BlendIn")` to `GetEventTime(anim.Reload.Erc.Reload_InsertMag, "BlendIn")` anim graph fix we were informed about for 1.2.1.66, that had broken inspection and reloading on most weapons.

**Comment by reyhard** [comment]
should be fixed in next RHS build
