### ISSUE TITLE
Spectrum Device Error Causing Crashes

### ISSUE THREAD

**Issue by Tex12Bravo** [RHSMODS/statusquo#996]
04.10 2024 19:00:31
Virtual Machine Exception

Reason: NULL pointer to instance. Variable 'm_Owner'

Class:      'RHS_RadioSourceActiveComponent'
Function: 'Register'
Stack trace:
scripts/Game/Weapon/Misc/SpectrumDevice/RHS_RadioSourceComponent.c:64 Function Register
scripts/Game/game.c:927 Function OnUpdate

Runtime mode

Pulled from crash logs. Multiple people being dashboarded/CTD. Some were crashed when accessing arsenal but most were being crashed randomly and en masse.

**Comment by ajvorobiev** [comment]
what version of the mod and game you are running?

**Comment by ajvorobiev** [comment]
Can you please provide the requested info or we will have to close the bug report as we are unable to reproduce.

**Comment by Tex12Bravo** [comment]
Most recent stable version on main stable branch of Arma Reforger

**Comment by ajvorobiev** [comment]
I dont think this is valid any more in experimental branch, but we'll keep it open for now.
